name: Build, Release & Publish (Forge 1.7.10)

on:
  push:
    branches:
      - 1.7.10/dev
  workflow_dispatch:

permissions:
  contents: write

env:
  NEXUS_URL: https://nexus-smc.mtechlab.dev/repository/maven-releases/
  MOD_VERSION: 1.0.${{ github.run_number }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: { fetch-depth: 0 }

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 8

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Setup CI workspace
        run: ./gradlew setupCIWorkspace

      - name: Build mod jars
        run: ./gradlew clean buildClient buildServer

      - name: Create version tag
        id: tag_version
        run: |
          TAG=$(./gradlew -q printTag)
          echo "TAG=$TAG" >> $GITHUB_ENV
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag $TAG && git push origin $TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG }}
          files: build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Nexus
        run: |
          ./gradlew publish \
            -PnexusUser=${{ secrets.NEXUS_USERNAME }} \
            -PnexusPass=${{ secrets.NEXUS_PASSWORD }} \
            -PmodVersion=${{ env.MOD_VERSION }}